openapi: 3.0.1
info:
  title: '@jupiterone/veracode-client'
  description: Veracode REST & XML API client
  x-cortex-git:
    github:
      repository: JupiterOne/veracode-client
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/veracode-client'
